version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - github-actions
    groups:
      github-actions:
        patterns:
          - '*'
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - npm
    groups:
      vitest:
        patterns:
          - vitest
          - '@vitest/*'
      npm-minor-patch:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
