export const EXAMPLE_CASES = [
  {
    name: 'demo',
    input: 'examples/demo-source.png',
    expectedBase: 'examples/demo',
    arguments: ['--preset', 'readme'],
  },
  {
    name: 'blocks-fine',
    input: 'tests/fixtures/character-styles/gradient.svg',
    expectedBase: 'examples/character-styles/blocks-fine',
    arguments: [
      '--style',
      'blocks-fine',
      '--width',
      '32',
      '--height',
      '8',
      '--oversample',
      '2',
      '--dither',
      'none',
    ],
  },
  {
    name: 'braille',
    input: 'tests/fixtures/character-styles/portrait.svg',
    expectedBase: 'examples/character-styles/braille',
    arguments: [
      '--style',
      'braille',
      '--width',
      '32',
      '--height',
      '20',
      '--oversample',
      '2',
      '--dither',
      'atkinson',
    ],
  },
  {
    name: 'structure',
    input: 'tests/fixtures/character-styles/structure.svg',
    expectedBase: 'examples/character-styles/structure',
    arguments: [
      '--style',
      'structure',
      '--width',
      '32',
      '--height',
      '32',
      '--oversample',
      '2',
      '--dither',
      'none',
      '--edge-threshold',
      '0.12',
    ],
  },
];
